### PR TITLE
ci: replaced the occurrence of allcontributors to allcontributors[bot]

### LINKED ISSUE #223: skipping workflows for `allcontributors` bot do not work
#### Describe the bug
Some workflows (https://github.com/search?q=repo%3Aasyncapi%2F.github+allcontributors+language%3AYAML&type=code&l=YAML) are designed to skip if `allcontributors` bot created a PR.

This is not working anymore

#### How to Reproduce

whenever you see a CI check in any repo, that is triggered by `allcontributors`, required steps are not skipped as expected

#### Expected behavior

we need skips as before

I think the problem is that the `actor` name has change. Now it is:

[allcontributors[bot]](https://github.com/asyncapi/cli/commits?author=allcontributors%5Bbot%5D)

so in all workflows from this repo, `allcontributors` must change to `allcontributors[bot]`

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
**Description**

- This replace all the occurrence of allcontributor to allcontributors[bot] for fixing the workflow.

**Related issue(s)**

Resolves #223

### CODE REVIEW

**Review by derberg — COMMENTED** [review]
@KhudaDad414 do you mind if I approve it and merge but stop replication? There are some more changes coming in like:
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- we need to migrate `actions/checkout@v2` to `actions/checkout@v3` because of `Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16`
- https://github.com/asyncapi/.github/pull/225

so still good to update all of these as separate PRs for granularity, but pushing to other repos could be done in one run. Thoughts?

**Comment by KhudaDad414** [comment]
@derberg Totally, it makes sense doing it that way. 😀

**Comment by derberg** [comment]
ok, working on https://github.com/asyncapi/.github/pull/226

**Comment by derberg** [comment]
you know what, forget it, lets merge this one. The other PR I mentioned is already big enough and will probably not be completed this week, so we can release this PR without waiting

**Pull request merged**
