### PR TITLE
ci: increase time on stale bot reaction and use latest version

### PR DESCRIPTION
**Pull request by derberg**
**Description**

- increase stale action to 120days. So issue is staled after 120days and then closed after 120, so it is 240 days before issues get closed.
- switch from v1 to v4 of stale action
- new version of stale action support removal of `stale` label after adding a comment (before you had to manually remove label)
- added more detailed message to stale action comment

The reason for the change is the increasing amount of issues/prs coming from the community, but the active contributors group is not growing at the same speed. We are not able to react to every single issue quickly enough to not get spammed by stale bot.

⚡ Important to notice ⚡ 
With this change, we can "unstale" issues with a comment, no need to manually remove the label. As a result, every maintainer should always favor the process of "unstaling by commenting" rather than "unstaling by removing the `stale` label".  Why? because this forces you (maintainer) to think why a given issue got stale, and also give hints on how to push a given issue forward. It is all about transparency and sending a clear messages to the community rather than expecting people to figure out the reason on their own.

### CODE REVIEW

**Review by smoya — APPROVED** [review]
Love it! Thanks

**Review by jonaslagoni — APPROVED** [review]
Sounds good to me 👍

**Review by magicmatatjahu — APPROVED** [review]
LGTM! 🚀

**Review by fmvilas — APPROVED** [review]
Awesome! 🚀

**Pull request merged**
