### PR TITLE
chore: remove not needed files and updated some links

### PR DESCRIPTION
**Pull request by pratik2315**
**Description**

- Removed some files (and put them in the asyncapi/community)
- Updated links to those deleted files and linked them to the community repo
- Updated meeting info in profile/README.md file

### CODE REVIEW

**Comment by pratik2315** [comment]
Hey @derberg ! I have made a new PR for this issue here. Can you pls check. Thanks for being so patient with me😅🙏

**Review by derberg — COMMENTED** [review]
I don't see any removed files information 🤔 

and don't worry it is taking some time, things happen 😄

**Review by derberg — APPROVED** [review]
❤️

**Review by derberg — APPROVED** [review]

**Pull request merged**
