### PR TITLE
ci: adapt cron and push workflows to run only on upstream

### LINKED ISSUE #164: Adding conditional statement to run scheduled workflows on main repository only
#### Describe the bug
Currently, the scheduled workflows are running on the master branch of the main repository and on forked repository of contributors as well. 
Also, I will be updating the help statement of `autoupdate` command in the bot regarding it doesn't update the PRs which are not ready to review or are in draft. 

#### Expected behavior
This issue targets to restrict the run of the scheduled workflows and they should only run periodically on master branch of main repository only.

### PR DESCRIPTION
**Pull request by akshatnema**
**Description**
This PR adds an `if` statement in each scheduled workflow to run in the main repository only. Also adds a comment that `autoupdate` workflow will not run or update the draft PRs in the repository.

**Related issue(s)**
Fixes #164

### CODE REVIEW

**Comment by akshatnema** [comment]
@derberg @KhudaDad414 Do review this PR and inform me if there is any error in implementation. I hope that I haven't made what I did in the previous one :crossed_fingers:.

**Review by derberg — APPROVED** [review]
LGTM 🚀 

thanks @akshatnema 🙏🏼 

@KhudaDad414 anything from you?

**Comment by akshatnema** [comment]
Hey, @derberg I just saw that `autoupdate` workflow runs on the fork every time a commit is pushed in my forked repo. Should I also make it run only on the main repo only?

**Comment by derberg** [comment]
yup, good eye! 🦅 👁️ 

autoupdate running on fork will always fail

**Comment by akshatnema** [comment]
@derberg Can you please look into the actions run on my fork repository in the last commit, I think I made something wrong in it. Here's the link to [Failed Github actions](https://github.com/akshatnema/.github/actions/runs/2333515552).

**Comment by derberg** [comment]
@akshatnema yeah, global workflow should not work on forks either

**Comment by akshatnema** [comment]
@derberg So this means that I should update them to not run in the forks. Right?

**Comment by derberg** [comment]
@akshatnema would be awesome 🙏🏼

**Comment by akshatnema** [comment]
@derberg Anything more need to be added?

**Comment by akshatnema** [comment]
> @akshatnema I updated PR title a bit, you ok with it?

Yeah, no problems at all.

**Review by derberg — APPROVED** [review]

**Comment by akshatnema** [comment]
Hey @derberg, are we going to wait for #159 to get merged before this PR?

**Comment by derberg** [comment]
@akshatnema no, actually I should have merged it already but forget. I do not like to merge these in the middle of the day as then replication to other repos occupy the CI, so I do it rather in the evenings when traffic is small. I hope I won't forget to merge it. And if I do, please merge it in your morning by adding a comment that I guess you know how it looks like, but I do not want to write it now to not trigger the merge :D

**Pull request merged**
