### PR TITLE
docs: fix link to meetings page

### PR DESCRIPTION
**Pull request by vishvamsinh28**
fixes :- https://github.com/asyncapi/website/issues/1947

### CODE REVIEW

**Review by anshgoyalevil — COMMENTED** [review]
LGTM 🚀 Thanks @vishvamsinh28

**Comment by anshgoyalevil** [comment]
@vishvamsinh28 Could you please update the issue description with GitHub Issue Linking Syntax ```fixes #issuenumber```, which helps close down the linked issue automatically on merge?

**Review by derberg — APPROVED** [review]
Thanks!

**Comment by derberg** [comment]
/rtm

please next time do not use autoformatter 😄 
and look into my change for the PR title. Then need to be descriptive

**Pull request merged**
