### PR TITLE
ci: add support for `next` release branch

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
In Modelina we have been using `next` since the beginning, however, we decided to remove it from the official workflow 🤨 We did a patch at some point in Modelina, and then I forgot about it.

This PR adds it officially.

### CODE REVIEW

**Comment by derberg** [comment]
don't you use also a global release config for sematic-release? 
we need change in https://github.com/asyncapi/.github/blob/master/.github/workflows/.releaserc as well

**Comment by jonaslagoni** [comment]
We dont no.

**Comment by jonaslagoni** [comment]
In the next branch we use a much more customized version: https://github.com/asyncapi/modelina/blob/next/.releaserc

**Comment by jonaslagoni** [comment]
I wonder if we should just remove Modelina from getting global CI change pushes...

**Comment by derberg** [comment]
@jonaslagoni as long as you do not provide modifications in release workflow, I do not recommend it.

release workflows are separated from release config with topics `get-global-node-release-workflows` and `get-global-releaserc` so that is fine and you have a flexibility you need at the moment. Just please update in this PR the release config, so semantic-release for others knows what to do with merges to `next`

**Comment by jonaslagoni** [comment]
@derberg done :v:

**Review by derberg — APPROVED** [review]

**Pull request merged**
