### PR TITLE
ci: fix release workflow to support release branches

### PR DESCRIPTION
**Pull request by char0n**
Refs https://github.com/asyncapi/spec/pull/834
Refs https://github.com/asyncapi/spec-json-schemas/pull/255

### CODE REVIEW

**Review by derberg — APPROVED** [review]

**Comment by char0n** [comment]
This was merged but haven't been propagated to https://github.com/asyncapi/spec/blob/master/.github/workflows/if-nodejs-release.yml and https://github.com/asyncapi/spec-json-schemas/blob/master/.github/workflows/if-nodejs-release.yml properly. Any advice?

**Comment by derberg** [comment]
- for https://github.com/asyncapi/spec it did not as `if-nodejs-release.yml` is actually a legacy file that should not be there. Spec is its own beast, with dedicated [release workflow](https://github.com/asyncapi/spec/blob/master/.github/workflows/release.yml). Updates for `if-nodejs-release.yml` and other node related workflow no longer go there as `nodejs` topic is not there on the repo. And in general, there is nothing node-related with this repo
- for https://github.com/asyncapi/spec-json-schemas I actually see all is good, and change was propagated properly https://github.com/asyncapi/spec-json-schemas/pull/256/files

**Comment by char0n** [comment]
Right, so I'll issue last PR that merges master to `next-spec` branch on `asyncapi/spec` repo and we should be fine there as well.

**Pull request merged**
