### PR TITLE
chore: remove welcome workflow due to its impact on infra

### PR DESCRIPTION
**Pull request by derberg**
Related to https://github.com/asyncapi/.github/issues/73

### CODE REVIEW

**Review by magicmatatjahu — APPROVED** [review]

**Comment by derberg** [comment]
@magicmatatjahu thanks for being so fast!

**Comment by magicmatatjahu** [comment]
@derberg I read issue and saw pinned PR, only that :P

**Comment by derberg** [comment]
@magicmatatjahu `only`? maybe `only` for you but for me it is 🚀 ❤️

**Comment by magicmatatjahu** [comment]
@derberg remember, you have a wife 😆  You're welcome :)

**Pull request merged**
