### PR TITLE
feat: update CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by smoya**
**Description**

We wrongly updated the CODE_OF_CONDUCT.md file [from community repo](https://github.com/asyncapi/community/pull/1132) instead of this one, which is the one being replicated around all our repositories.

This PR moves the changes into the file in this repository + some fixes. Additionally, making the @asyncapi/code_of_conduct  team owner of such a file.

### CODE REVIEW

**Review by derberg — DISMISSED** [review]

**Comment by smoya** [comment]
@derberg does it make sense to keep this PR opened until this is resolved https://github.com/asyncapi/community/issues/1235 ? Otherwise, If you think of a temporary solution for the meantime...

**Review by alequetzalli — APPROVED** [review]
🚢

**Comment by derberg** [comment]
@smoya I need to do some dns changes and hand over dns management to LF so we can start getting redirects like conduct@asyncapi.com from them. One week more is needed

**Comment by smoya** [comment]
@derberg is this mergeable now?

**Comment by derberg** [comment]
sorry, holidays. I got confirmation from LF, just need to do some exports from netlify and provide them to LF so now they control it - and this way we will get the redirects working. I just need more time to do it. Please reopen @smoya as I cannot

**Comment by smoya** [comment]
@derberg thanks for the update! I will reopen once Im back from holidays (i had to remove my fork for a reason).

**Comment by smoya** [comment]
I created a new PR that overrides this one https://github.com/asyncapi/.github/pull/310 cc @derberg

**Pull request closed without merging**
