### PR TITLE
ci: extend welcome message with more details about contributions

### PR DESCRIPTION
**Pull request by derberg**
**Description**

- extend welcome message with more details about contributions

### CODE REVIEW

**Review by fmvilas — APPROVED** [review]
That was quick! 👏

**Review by fmvilas — APPROVED** [review]
I can see [too many things are quick](https://twitter.com/derberq/status/1353694503442534403) in your life lately :trollface:

**Comment by derberg** [comment]
@fmvilas

**Comment by fmvilas** [comment]
Neverending story 🎶

**Pull request merged**
