### PR TITLE
ci: improve out-of-date message on PRs + some other minor issues

### LINKED ISSUE #158: False negatives in local links
#### Describe the bug
Recently introduced check for Links that run weekly gives false negatives in all of the local markdown links. 
as you can see in the latest run (https://github.com/asyncapi/generator/runs/6050625807?check_suite_focus=true) all of the local links that point to some section of the same file or other local files, gives `404` error. 

#### Expected behaviour
They should pass since I can click on them and they work perfectly.

#### Root of the issue
After checking the links with other link checkers online, I see all of them give 404 errors unless the link is opened by a browser. I assume it is some kind of protection against bots by GitHub.

#### Possible Solution
I guess we should ignore local links?

### PR DESCRIPTION
**Pull request by KhudaDad414**
**Description**

- Don't show the out-of-date message if the branch is not protected.
for example:  https://github.com/asyncapi/spec-json-schemas/pull/199#issuecomment-1097698492, https://github.com/asyncapi/spec/pull/584#issuecomment-1099024685

fixes #158

### CODE REVIEW

**Comment by derberg** [comment]
could you also, in this PR start using new `SLACK_CI_FAIL_NOTIFY` secret for:
- https://github.com/asyncapi/.github/blob/master/.github/workflows/link-check-cron.yml#L35
- https://github.com/asyncapi/.github/blob/master/.github/workflows/automerge-orphans.yml#L60

🙏🏼

**Comment by KhudaDad414** [comment]
@derberg made the changes.

**Review by derberg — APPROVED** [review]
🚀 :shipit:

**Pull request merged**
